apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
  name: cip-enabled
spec:
  adminCredentialRef:
    name: avi-controller-credentials
    namespace: tkg-system-networking
  certificateAuthorityRef:
    name: avi-controller-ca
    namespace: tkg-system-networking
  cloudName: vcsa-01a
  clusterSelector:
    matchLabels:
      cip-enabled: "true"
  controller: avi-01a.corp.local
  dataNetwork:
    cidr: 172.16.110.0/24
    name: ov-tkg-vip
  extraConfigs:
    disableStaticRouteSync: false                               # required
    #    image:
    #  pullPolicy: IfNotPresent
    #  repository: projects.registry.vmware.com/tkg/ako
    #  version: v1.3.2_vmware.1
    ingress:
      disableIngressClass: false                                # required
      nodeNetworkList:                                          # required
        - cidrs:
            - 172.16.80.0/24
          networkName: ov-tkg
      serviceType: ClusterIP                                    # required
      shardVSSize: MEDIUM                                       # required
  serviceEngineGroup: se-group-01
